[build]
command = "composer install --no-dev --prefer-dist --no-interaction --no-progress --optimize-autoloader"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=\$PORT"

[env]
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:Tq10ZYNF64apwpe8e9vFaTFMW1wvM0BGMU1mgmfKL0I="
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"
APP_ROLE = "web"
RUN_MIGRATIONS = "1"
SCHEDULER_INTERVAL = "60"

# Filament Admin Panel
FILAMENT_BASE_URL = "admin"

# Database
DB_CONNECTION = "mysql"
DB_HOST = "${{MYSQLHOST}}"
DB_PORT = "${{MYSQLPORT}}"
DB_DATABASE = "${{MYSQLDATABASE}}"
DB_USERNAME = "${{MYSQLUSER}}"
DB_PASSWORD = "${{MYSQLPASSWORD}}"

# Cache / Queue / Sessions
CACHE_DRIVER = "redis"
SESSION_DRIVER = "redis"
QUEUE_CONNECTION = "redis"
REDIS_CLIENT = "phpredis"
REDIS_HOST = "${{REDISHOST}}"
REDIS_PASSWORD = "${{REDISPASSWORD}}"
REDIS_PORT = "${{REDISPORT}}"
REDIS_PREFIX = "lucrativabet_"

# JWT and Security
JWT_SECRET = "UEG52HCZ4N8WKDQMNX7VLIP3J9C8A2NNB78PTFQ3E1LK4VPNIMOP5X8YMGD1PXWB"
